Imports System.Reflection.Emit
Imports System.Windows.Forms.VisualStyles.VisualStyleElement.Button

Module Module_Language
    Public Sub to_en()
        form_main.Text = "EasyMiner" + " ver. " + version
        form_main.文件ToolStripMenuItem.Text = "File"
        form_main.载入参考序列ToolStripMenuItem.Text = "Load References"
        form_main.测序文件ToolStripMenuItem.Text = "Load Sequencing Files"
        form_main.下载序列ToolStripMenuItem.Text = "Download References"
        form_main.下载叶绿体基因组ToolStripMenuItem.Text = "Plant Chloroplast Genome"
        form_main.下载植物线粒体ToolStripMenuItem.Text = "Plant Mitochondrial Genome"
        form_main.哺乳动物线粒体基因组ToolStripMenuItem.Text = "Animal Mitochondrial Genome"
        form_main.下载ToolStripMenuItem.Text = "Angiosperm 353 Genes"
        form_main.导出ToolStripMenuItem.Text = "Export List"
        form_main.导出参考序列ToolStripMenuItem.Text = "Export References"
        form_main.导出测序文件ToolStripMenuItem.Text = "Export Sequencing Files"
        form_main.刷新数据ToolStripMenuItem.Text = "Refresh Data"
        form_main.过滤ToolStripMenuItem.Text = "Filter"
        form_main.从头过滤ToolStripMenuItem.Text = "Filter from Scratch"
        form_main.进一步过滤ToolStripMenuItem.Text = "Further Filter"
        form_main.拼接ToolStripMenuItem.Text = "Assemble"
        form_main.全自动ToolStripMenuItem.Text = "Filter + Assemble"
        form_main.迭代ToolStripMenuItem.Text = "Iteration"
        form_main.迭代ToolStripMenuItem1.Text = "First Iteration"
        form_main.重新拼接ToolStripMenuItem.Text = "Re-Assemble"
        form_main.多次迭代ToolStripMenuItem.Text = "Multiple Iterations"
        form_main.重构ToolStripMenuItem.Text = "Generate Consensus"
        form_main.多拷贝检测ToolStripMenuItem.Text = "Paralog Detection"
        form_main.植物叶绿体基因组ToolStripMenuItem.Text = "Plant Chloroplast Genome"
        form_main.植物线粒体基因组ToolStripMenuItem.Text = "Plant Mitochondrial Genome"
        form_main.哺乳动物线粒体基因组ToolStripMenuItem1.Text = "Animal Mitochondrial Genome"
        form_main.长读条码ToolStripMenuItem.Text = "Long Read Analysis"
        form_main.分离序列ToolStripMenuItem.Text = "Separate Barcodes"
        form_main.合并结果ToolStripMenuItem1.Text = "Merge Results"
        form_main.重建序列ToolStripMenuItem.Text = "Reconstruct Sequences"
        form_main.分离重建ToolStripMenuItem.Text = "Separate && Reconstruct"
        form_main.批量ToolStripMenuItem1.Text = "Batch"
        form_main.过滤拼接ToolStripMenuItem.Text = "Filter && Assemble"
        form_main.合并结果ToolStripMenuItem.Text = "Merge Results"
        form_main.合并比对ToolStripMenuItem.Text = "Merge && Trim"
        form_main.重构序列ToolStripMenuItem.Text = "Generate Consensus"
        form_main.旁系同源检测ToolStripMenuItem.Text = "Paralog Detection"
        form_main.PPDToolStripMenuItem.Text = "PPD (for 353 only)"
        form_main.ToolStripMenuItem2.Text = "Plant Chloroplast Genome"
        form_main.ToolStripMenuItem3.Text = "Plant Mitochondrial Genome"
        form_main.哺乳动物线粒体基因组ToolStripMenuItem2.Text = "Animal Mitochondrial Genome"
        form_main.统计结果ToolStripMenuItem.Text = "Summary Statistics"
        form_main.三方工具ToolStripMenuItem.Text = "Other Tools"
        form_main.序列比对ToolStripMenuItem1.Text = "Sequence Alignment"
        form_main.切齐比对ToolStripMenuItem1.Text = "Trimmed Alignment"
        form_main.RichTextBox1.Text = "Double-click to view logs"
        form_main.分析ToolStripMenuItem.Text = "Analysis"
        form_main.GroupBox1.Text = "Output"
        form_main.Label3.Text = "Threads"
        form_main.Button1.Text = "Change"
        form_main.Button2.Text = "Open"

        form_main.EnglishToolStripMenuItem.Text = "中文"
        language = "EN"

    End Sub

    Public Sub to_ch()
        form_main.Text = "EasyMiner" + " ver. " + version
        form_main.文件ToolStripMenuItem.Text = "文件"
        form_main.载入参考序列ToolStripMenuItem.Text = "载入参考序列"
        form_main.测序文件ToolStripMenuItem.Text = "载入测序文件"
        form_main.下载序列ToolStripMenuItem.Text = "下载序列"
        form_main.下载叶绿体基因组ToolStripMenuItem.Text = "植物叶绿体基因组"
        form_main.下载植物线粒体ToolStripMenuItem.Text = "植物线粒体基因组"
        form_main.哺乳动物线粒体基因组ToolStripMenuItem.Text = "动物线粒体基因组"
        form_main.下载ToolStripMenuItem.Text = "被子植物353基因"
        form_main.导出ToolStripMenuItem.Text = "导出列表信息"
        form_main.导出参考序列ToolStripMenuItem.Text = "导出参考序列"
        form_main.导出测序文件ToolStripMenuItem.Text = "导出测序文件"
        form_main.刷新数据ToolStripMenuItem.Text = "刷新数据"
        form_main.过滤ToolStripMenuItem.Text = "过滤"
        form_main.从头过滤ToolStripMenuItem.Text = "从头过滤"
        form_main.进一步过滤ToolStripMenuItem.Text = "进一步过滤"
        form_main.拼接ToolStripMenuItem.Text = "拼接"
        form_main.全自动ToolStripMenuItem.Text = "过滤&&拼接"
        form_main.迭代ToolStripMenuItem.Text = "迭代"
        form_main.迭代ToolStripMenuItem1.Text = "首次迭代"
        form_main.重新拼接ToolStripMenuItem.Text = "重新拼接"
        form_main.多次迭代ToolStripMenuItem.Text = "多次迭代"
        form_main.重构ToolStripMenuItem.Text = "一致性重构"
        form_main.多拷贝检测ToolStripMenuItem.Text = "旁系同源检测"
        form_main.植物叶绿体基因组ToolStripMenuItem.Text = "植物叶绿体基因组"
        form_main.植物线粒体基因组ToolStripMenuItem.Text = "植物线粒体基因组"
        form_main.哺乳动物线粒体基因组ToolStripMenuItem1.Text = "动物线粒体基因组"
        form_main.长读条码ToolStripMenuItem.Text = "长读分析"
        form_main.分离序列ToolStripMenuItem.Text = "分离条码"
        form_main.合并结果ToolStripMenuItem1.Text = "合并结果"
        form_main.重建序列ToolStripMenuItem.Text = "重建序列"
        form_main.分离重建ToolStripMenuItem.Text = "分离&&重建"
        form_main.批量ToolStripMenuItem1.Text = "批量"
        form_main.过滤拼接ToolStripMenuItem.Text = "过滤&&拼接"
        form_main.合并结果ToolStripMenuItem.Text = "合并结果"
        form_main.合并比对ToolStripMenuItem.Text = "合并&&切齐"
        form_main.重构序列ToolStripMenuItem.Text = "一致性重构"
        form_main.旁系同源检测ToolStripMenuItem.Text = "旁系同源检测"
        form_main.PPDToolStripMenuItem.Text = "PPD (仅用于353)"
        form_main.ToolStripMenuItem2.Text = "植物叶绿体基因组"
        form_main.ToolStripMenuItem3.Text = "植物线粒体基因组"
        form_main.哺乳动物线粒体基因组ToolStripMenuItem2.Text = "动物线粒体基因组"
        form_main.统计结果ToolStripMenuItem.Text = "统计汇总结果"
        form_main.三方工具ToolStripMenuItem.Text = "其他"
        form_main.序列比对ToolStripMenuItem1.Text = "序列比对"
        form_main.切齐比对ToolStripMenuItem1.Text = "切齐比对"
        form_main.RichTextBox1.Text = "双击此处查看最近的日志"
        form_main.分析ToolStripMenuItem.Text = "分析"
        form_main.EnglishToolStripMenuItem.Text = "English"
        form_main.GroupBox1.Text = "输出目录"
        form_main.Label3.Text = "进程数量"
        form_main.Button1.Text = "更改目录"
        form_main.Button2.Text = "打开目录"
        language = "CH"


    End Sub
End Module
